spring:
  application:
    name: ms-admin-api-gateway
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
         max-attempts: 20
         max-interval: 15000
         initial-interval: 10000

